version: '3.8'

services:
  discord-bot:
    build:
      context: .
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - expressjs-server

  expressjs-server:
    build:
      context: /Users/james/Documents/api-typescript/ExpressJs
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
